### ISSUE TITLE
review existing content [module]

### ISSUE THREAD

**Issue by mayarichman** [levelupcc/level-up#15]
[[ Module Review Checklist ]]
+ Grammar/Syntax/Voice check
+ Fix dates (Month YYYY)
+ Add in all missing hyperlinks (external and internal to site)
+ Add in any missing URLs for ADIDS Elements on <module> pages
+ Add in additional parent themes for modules with more than one
+ Fix spacing between summary blocks and content blocks
+ Hyperlink resource titles on respective parent pages
+ Link to download .md version

**Comment by megdeb** [comment]
reviewing remaining content:
- creating and managing strong passwords
- safer browsing: HTTPS and SSL
- data backup
- safer browsing: identity protection and privacy

**Comment by nicsrlv** [comment]
Will do pre-launch review pass of all content in site-view, once all modules are complete.
