### ISSUE TITLE
make navigation push section down, rather than cover the section

### ISSUE THREAD

**Issue by mayarichman** [levelupcc/level-up#62]
[LUP_horizontal_navigation.pdf](https://github.com/the-engine-room/level-up/files/245008/LUP_horizontal_navigation.pdf)

**Comment by nicsrlv** [comment]
@hedr @mayarichman is this for all pages or just sub-pages (i.e. everything except home page?)

**Comment by ghost** [comment]
@nicsrlv i think it's everything including the home page. when do you need this ready?

**Comment by nicsrlv** [comment]
@hedr angling to launch by thursday (6/30) in the morning DC time :)  is that doable?

**Comment by ghost** [comment]
@nicsrlv probably not. but i can work on this post-launch if that's okay?
